### ISSUE TITLE
Conda recipe for v2.10.0

### ISSUE THREAD

**Issue by valeriupredoi** [conda-forge/esmvaltool-suite-feedstock#23]
## Removals

- Julia build:
```
  # - name: esmvaltool-julia
  #   build:
  #     noarch: generic
  #     post-link: install-julia-deps
  #   requirements:
  #     run:
  #       - esmvaltool-python
```

## Package pins

- `esmvalcore 2.10.*`
- `iris >=3.6.0`

in esmvaltool:

```
    requirements:
      host:
        - python >=3.8
      run:
        - python >=3.8
```
-> that needs to be 3.9

attn: @zklaus @bouweandela

Also maybe remove Remi as maintainer?
